version: 2.1

executors:
  node:
    parameters:
      image:
        type: string
        default: '10.13'
    docker:
      - image: circleci/node:<< parameters.image >>

jobs:
  test:
    executor: node
    steps:
      - checkout
      - run: yarn --frozen-lockfile
      - run: yarn test

workflows:
  version: 2

  test:
    jobs:
      - test
