- meta:
    id: 1
    sku: CH465517080
    createdAt: 2020-10-01
  name: Sliding screen tablet
  description: Slide-able screen tablet/phone usable wherever you go. Also really durable
  appearance: Season 3
- meta:
    id: 2
    sku: SV4680468050
    createdAt: 2020-10-02
  name: Wafers
  description: Digestible smart electronics that can transmitt some kind of experience or meditation to one's head
  appearance: Season 3
