language: node_js
node_js:
  - '6'
dist: trusty
addons:
  chrome: stable
before_install:
  - if [[ `npm -v` != 3* ]]; then npm i -g npm@3; fi
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1920x1080x16"
  # give xvfb some time to start
  - sleep 3
before_script:
  # Same as what we specified for Xvfb.
  - "export DISPLAY=:99.0"
  - cp test/setup.js.travis test/setup.js
  # Start https server (and sleep) so we can get the local bundle.js via https.
  - npm run serve-https-local > /dev/null 2>&1 &
  - sleep 3
cache:
  directories:
    - node_modules
sudo: false
# When the test script fails, push screen shots to a git branch.
after_failure: |
  if [ -n "$GITHUB_API_KEY" ]; then
    cd "$TRAVIS_BUILD_DIR/travis-screenshots"
    git init
    git checkout -b travis-screenshots
    git add .
    git -c user.name="$GITHUB_USER" -c user.email='travis' commit -m 'Travis CI screenshots'
    # Make sure to make the output quiet, or else the API token will leak!
    # This works because the API key can replace your password.
    git push -f -q https://$GITHUB_USER:$GITHUB_API_KEY@github.com/$TRAVIS_REPO_SLUG travis-screenshots &2>/dev/null
    cd "$TRAVIS_BUILD_DIR"
  fi