[build]
  Command = "yarn build"
  Publish = "build"

[build.environment]
  CI = "true"
  YARN_VERSION = "1.6.0"
  NPM_CONFIG_PRODUCTION = "false"

[[redirects]]
  from = "/storybook"
  to = "/storybook/index.html"
  status = 301
  force = true
