minVersion: '0.14.0'
github:
  owner: getsentry
  repo: sentry-javascript
changelogPolicy: simple
statusProvider:
  name: github
artifactProvider:
  name: github
preReleaseCommand: bash scripts/craft-pre-release.sh
targets:
  - name: npm
  - name: github
    includeNames: /^sentry-.*$/
  - name: gcs
    includeNames: /.*\.js.*$/
    bucket: sentry-js-sdk
    paths:
      - path: /{{version}}/
        metadata:
          cacheControl: 'public, max-age=31536000'
  - name: registry
    type: sdk
    onlyIfPresent: /^sentry-browser-.*\.tgz$/
    includeNames: /\.js$/
    checksums:
      - algorithm: sha384
        format: base64
    config:
      canonical: 'npm:@sentry/browser'
  - name: registry
    type: sdk
    onlyIfPresent: /^sentry-node-.*\.tgz$/
    config:
      canonical: 'npm:@sentry/node'
  - name: registry
    type: sdk
    onlyIfPresent: /^sentry-react-.*\.tgz$/
    config:
      canonical: 'npm:@sentry/react'
  - name: registry
    type: sdk
    onlyIfPresent: /^sentry-vue-.*\.tgz$/
    config:
      canonical: 'npm:@sentry/vue'
  - name: registry
    type: sdk
    onlyIfPresent: /^sentry-gatsby-.*\.tgz$/
    config:
      canonical: 'npm:@sentry/gatsby'
  - name: registry
    type: sdk
    onlyIfPresent: /^sentry-angular-.*\.tgz$/
    config:
      canonical: 'npm:@sentry/angular'
  - name: registry
    type: sdk
    onlyIfPresent: /^sentry-wasm-.*\.tgz$/
    config:
      canonical: 'npm:@sentry/wasm'
  - name: aws-lambda-layer
    includeNames: /^sentry-node-serverless-\d+(\.\d+)*\.zip$/
    layerName: SentryNodeServerlessSDK
    compatibleRuntimes:
      - name: node
        versions:
          - nodejs10.x
          - nodejs12.x
          - nodejs14.x
    license: MIT
